[aliases]
"Aida GD" = ["Aida"]
"Alberto GR" = ["Alberto Guerra"]
"Alberto TL" = ["Alberto Téllez"]
"Alejandro GZ" = ["Alejandro", "Alejandro González Zapico"]
"Alejandro PG" = ["Alejandro Perez"]
"Alfonso GV" = ["Alfonso"]
"Arantzazu ST" = ["Arantzazu"]
"Carmen TG" = ["Carmen"]
"David CG" = ["David", "David Conde"]
"David GG" = []
"David VG" = ["David Vazquez"]
"Diego TM" = ["Diego", "Diego Trapiello"]
"Javi CC" = ["Javi"]
"Jorge Pg" = ["Jorge", "Jorge Puente", "Jorge Puente García", "Jorge PG"]
"Jose RB" = []
"Juan MB" = ["Juan"]
"Manuel AC" = ["Manu"]
"Marcos AP" = []
"Melany JC" = ["Melany"]
"Nacho LA" = ["Nacho", "Nacho López"]
"Angel MR" = ["Ángel", "Angel", "Ángel MR", "Ángel Macías Rodríguez", "Angel Macias Rodriguez"]
